title = "Bookish Musings by A"
baseURL = "https://bookishmusings.netlify.app"
languageCode = "en-us"
theme = "gohugo-theme-ananke"
resourceDir = "../resources"
enableEmoji = "true"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3                  # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
[languages.en]
title = "Bookish Musings by A"
weight = 1
contentDir = "content/en"
# languageDirection = 'rtl' for Right-To-Left languages

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
font = "Open Sans"
text_color = ""
author = ""
favicon = ""
site_logo = ""
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-black"
recent_posts_number = 3

[[params.ananke_socials]]